### ISSUE TITLE
Generating application Error

### ISSUE THREAD

**Issue by hoaibac** [fooll/fooll#1]
Generating application: appName
The syntax of the command is incorrect.
child_process.js:634
    throw err;
    ^

Error: Command failed: mkdir appName/
The syntax of the command is incorrect.

**Comment by burawi** [comment]
Are you using windows ?

**Comment by hoaibac** [comment]
@burawi  Yes, i used using windows

**Comment by burawi** [comment]
ok it's because mkdir command(the command that creates directory) does not exist in windows!
We'll fix it right now

**Comment by burawi** [comment]
update using:
`npm i -g fooll-cli`
it should work now!

**Comment by yassin-mokni** [comment]
you mean `fooll-cli` not `fool-cli`

**Comment by hoaibac** [comment]
I'll try again

**Comment by hoaibac** [comment]
@yassinMk I used Windows 10 Pro x64
 
Error: Command failed: mkdir

**Comment by burawi** [comment]
@hoaibac Sorry man! I forgot to publish the update on npm retry now

**Comment by burawi** [comment]
@hoaibac did you try ?
