### ISSUE TITLE
how disable  console log 

### ISSUE THREAD

**Issue by tablecell** [fooll/fooll#5]
like  in express 
```
   //  this.use(express.logger());
```
in debug mode  output  request log to console 
in production mode   comment log to disable log

**Comment by burawi** [comment]
The feature was added.
Install the latest version (2.3.7)
```
npm i zinky@latest --save
```
Then set `logRequest` property to app instance to `false` if you want to stop request logs. It is by default set to `true`.

Eg:
```javascript
const Zinky = require("zinky");
const app = new Zinky({
    logRequest: false
})
```

**Comment by burawi** [comment]
@tablecell did that solve your problem, so I can close the issue ?

**Comment by tablecell** [comment]
> 
> 
> @tablecell did that solve your problem, so I can close the issue ?

yes  problem solved
